model_path: unlearning_ckpt2/ft_model_10_epochs_inst_lr1e-3
model_family: llama2-7b

save_dir: ${model_path}

data_path: [MUSE_data_news, MUSE_data_news, MUSE_data_news]

split: forget10

split_list:
  - forget10
  - forget10
  - forget10

question_key: [question, question, question]
answer_key: [answer, answer, answer]

base_answer_key: [paraphrased_answer, paraphrased_answer, paraphrased_answer]
perturbed_answer_key: [perturbed_answer, perturbed_answer, perturbed_answe]


eval_task: [eval_log_forget, eval_log_forget, eval_log_forget]

generation:
  max_length: 100 
  max_new_tokens: null
#reduced gen length from 200
save_generated_text: true

ds_size: 300

overwrite: true
use_pretrained: false

batch_size: 100
#For first run
#gamma_list: [1.0]

#For second run
#gamma_list: [-1.0]

#For third run
#gamma_list: [-2.0]


logsoftmax_list: [True]
sample_list: [False]


#logsoftmax_list: [True, True, True]
#sample_list: [False, False, False]
